language: julia
dist: trusty
sudo: true
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
script:
  - julia -e 'Pkg.clone("https://github.com/zenna/Spec.jl")'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Arrows")'
  - julia -e 'Pkg.add("MacroTools")'
  - julia -e 'Pkg.add("Memoize")'
  # Make this conditiona on 0.7
  - julia -e 'Pkg.checkout("LightGraphs")'
  - julia -e 'Pkg.test("Arrows", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Arrows")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Arrows")); include(joinpath("docs", "make.jl"))'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
